project:
    type: website
    output-dir: docs
    resources:
        - "lecture-scripts/*"
        - "assignments"
        - "lecture-notes/*.ipynb"

website:
    body-footer: |
        <br> <br> <span style="color:grey;">&#169; Phil Chodrow, 2023</span>
    sidebar:
        collapse-level: 1
        style: "docked"
        title: "Senior Thesis: CSCI 0702"
        subtitle: test
        contents:
            - syllabus.qmd
            - text: "Schedule"
              file: index.qmd
            - text: "Thesis Deliverables"
              file: deliverables/thesis.qmd 
            - resources.qmd
    favicon: assets/icons/favicon.png
    

format:
    html:
        theme: [cosmo, assets/css/custom.scss]
        css: assets/css/styles.css
        toc: true
        number-depth: 0
        reference-location: margin
        callout-icon: false;
        callout-appearance: simple
        bibliography: refs.bib

execute:
    cache: true
