---
title: Thesis Proposal
---

By the end of Winter Term, you will write a **thesis proposal**. This proposal describes the work that you have already done, the work that you will do in the spring, and the overall scientific accomplishment that your thesis will represent. Your thesis proposal is proof that you *have a plan* for completing an interesting and high-quality project. 

During Winter term, we'll work on your thesis proposal through a sequence of assignments. 

## What? 

Please create a very short presentation of **3 slides** (not including your title slide). You should have one slide that addresses each of the following questions: 

1. What is the thing that I am going to do?
2. Why am **I** interested in or excited about that? 
    - *Note: at this point, you don't have to justify why anyone* ***else*** *should be interested in or excited about it.*
3. If I am completely successful, what would the outcome of my work be? 


You should expect that your in-class presentation will take no longer than 5 minutes. 

**Please do** use graphics, diagrams, and technical language used in the area in which you are studying.  

**Please don't** worry about the question of "why is this important?" We'll address that question in a future presentation. 

**Submit a PDF of your slides on Canvas and be ready to present in class!** 

## Why? 

Now it's time to clearly state the "*why?*" of your work. Please create a brief presentation of 5 slides (not including your title slide). Each of your slides should address one of the following sets of questions:

1. What is the thing that I am going to do? (*This can be a revision of slides in your "What?" presentation.*)
2. Why should people care about that thing getting done? 
3. What previous work exists that has attempted to solve my problem, or closely-related problems?
4. What is the "gap" in this work? Why is there still more work left to do in this area?
5. What's my angle? What's the idea or secret sauce that makes me believe that I can address this gap in a useful way? 

**Please do** use graphics, diagrams, and technical language used in the area in which you are studying.  

**Please don't** get too bogged down in making your slides look extremely fancy.   



**Submit a PDF of your slides on Canvas and be ready to present in class!** 





<!-- ## How?

Ok, so you know what you want to do and you know why we should care that you do it. ***How*** are you going to make it happen? Please create a brief presentation of 7 slides (not including your title slide) in which you address how you'll pursue your thesis research. Please organize your slides in the following sequence: 

[Slides 1, 2, and 3 can (and should!) be remixes from the **What?** and **Why?** presentations.]{.aside} 

1. Reminder: what am I doing? 
2. Reminder: why should folks care that I am doing it? 
3. Reminder: How have other folks approached this problem in the past? 
4. What is the big-picture strategy for my approach? How did I (or my advisor) choose that strategy? 
5. How does what I have *already* done fit into that strategy? What's the rest of my roadmap, as best I can see it? 
6. What is the major *obstacle* or *challenge* that I can foresee that could potentially disrupt my ability to execute the approach? 
7. What is my area of focus over the next ~50 hours or so of work? 

**Please do** use graphics, diagrams, and technical language used in the area in which you are studying.  

**Please don't** get too bogged down in making your slides look extremely fancy. 

**Submit a PDF of your slides on Canvas and be ready to present in class!**  -->

## Thesis Proposal Presentation

Your thesis proposal presentation includes two deliverables: 

### Proposal Presentation Outline

Your thesis proposal presentation is an 11-slide, 11-minute presentation in which you describe your research question, summarize your achievements so far, and describe what you will do next. You can think of it as a synthesis of **What?**, **Why?**, with aspects that look both forward and backward. Unlike the previous presentations we've done in this class, this presentation should be structured and professional. We'll be inviting the CS faculty to attend your proposal presentation. 

Because the proposal is a more formal presentation, I am going to ask you to **outline** it ahead of time. Your outline should be based on the strategy described in Part 1 of [these slides](https://drive.google.com/file/d/13efH6iA6toPtJ91KBt_QCeAyQBcSN7SA/view) by [Dan Larremore](https://larremorelab.github.io/). In particular, your outline (and your slides) should be structured exactly as: 

1. Title
2. Intro: entice audience. This is probably the right place to explain the problem and why it is important. 
3. Intro: hook audience (now they are fully paying attention). This is a good place to expand on the importance of the problem, describe what has been done before, and hint at the secret sauce that is going to make you successful. 
4. Outline: what content you are about to share with them. 
5. [Results]
6. [Results]
7. [Results]
8. [Results]
9. Summary: remind the audience of what you've shared so far. 
10. Outline of plans for the spring semester: what do you need to do and how will you do it? 
11. Thanks + acknowledgements. 

Each of these slides needs to be relatively simple: you should plan to spend approximately 1 minute on each (possibly less on title slide and thanks + acknowledgments). 

Your outline can be an entry in your reflection journal on Overleaf. Submit a PDF on Canvas. 

**Required Outline Components**

- 1-2 sentences describing *the idea* of your project. What will folks say when they are asked what your talk was about?
- A few sentences describing what you know about your audience and how you will factor that knowledge into your presentation strategy. (Note: your audience is your classmates + CS faculty)
- For each of your 11 slides, write a sentence that describes the purpose of the slide (motivating the topic, explaining a preliminary result, describing an approach, summarizing what has been learned). Your sentences should be unique and specific in the context of *your* project. 
    - So, "In this slide, I will hook the audience" is not unique or specific. 
    - "In this slide, I will highlight the gap in scholarship about X and hint that I am going to use Y to address this."

### Proposal Presentation

Your proposal presentation should be a set of professional, polished slides that implement the outline you submitted above. Before crafting your presentation, please take time to completely read through [these slides](https://drive.google.com/file/d/13efH6iA6toPtJ91KBt_QCeAyQBcSN7SA/view) by [Dan Larremore](https://larremorelab.github.io/). A few simple points are especially important: 

1. All figures need to have axis labels and a *message* that contributes to the purpose of the slide. 
2. No small fonts. 
3. Exactly 11 slides, timed for exactly 11 minutes. Practice ahead of time! 

That said, the more you adapt from Dan's guidance, the better your presentations will be. 

**Submit a PDF of your slides on Canvas and be ready to present in class!**  

## Thesis Proposal Document

Your thesis proposal is a written version of your proposal presentation. You can think of it as the capstone deliverable for CSCI 0702 in W24. It should include the following sections: 

- **Abstract**: Give a concise, one-paragraph summary of your proposal document. 
- **Introduction**: Describe the problem you aim to solve and why it's important. This is a good place to cite "big picture" papers that don't necessarily address your problem but do underscore why it matters. You can also close this section with a paragraph describing what *you* are going to do and how it is promisingly different from what has been done before. 
- **Related Work**: Give a written overview of prior literature that addresses your problem or related versions of your problem. 
- **Methods**: Describe *your* approach to your problem -- algorithms, math, software frameworks, experiments. 
- **Results**: Describe the results of your work so far. This is a good place to include appropriately labeled figures **with discussion**, as well as tables and other artifacts produced from your findings so far. Your focus in this sectino should be on ensuring that the reader understands what the results literally mean and how they relate to each other. Questions of importance or big-picture framing are for the following section. 
- **Discussion**: Describe the significance and limitations of your results. Here is the place to emphasize the importance of your results in the context of your overall research motivation. 
- **Future Work**: Describe the gap between what you've achieved so far and what you've set out to do. What's left? Describe your plan for the remainder of your work, your vision of full success, and a possible "partial success" scenario that would still allow you to addres the primary motivation of your project. 

#### Specifications

- Please include all of the sections above, in the described order. 
- Your proposal should be 4-6 single-spaced pages (or 8-12 double-spaced pages), not including references. 
- Related, please use appropriate citations in LaTeX and generate a references section. 
- Proposals are a polished, professional written artifact. They should therefore be drafted and revised! 
- Writing tactics: 
    - [No weasel words](https://matt.might.net/articles/shell-scripts-for-passive-voice-weasel-words-duplicates/).
    - When structuring a results section, I often find it helpful to generate my figures (and captions) *first*, and then build my story around them. 
    - Your story is a narrative of your scientific findings, not of the work you did to get them. If you spent a lot of time on something that ultimately didn't work out, you should spend at most a few sentences in your proposal explaining what you did, why it didn't work, and how that's relevant to what *did* work. 



